development:
  adapter: postgresql
  encoding: unicode
  database: cards_development
  pool: 5
  # username: postgres
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: cards_test
  pool: 5
  # username: postgres
  timeout: 5000